[session]
version=3
selectedTab=8
[file_000]
path=LegoScript.bas
scroll=174
cursor=25231
encoding=UTF-8
eolMode=CRLF
folds=62,66,96,104,119,124,177,197,250,264,274,323,376,401,428,435,444,457,483,539,604,640,648,1060,1117,1231,1236
[file_001]
path=LSModules/LS2LDR.bas
scroll=33
cursor=3444
encoding=UTF-8
eolMode=CRLF
folds=26,63,68,77,90,114,929
[file_002]
path=Loader/LoadLDR.bas
scroll=0
cursor=3251
encoding=UTF-8
eolMode=CRLF
folds=74,616,1046,1071
[file_003]
path=Loader/Modules/Model.bas
scroll=55
cursor=62782
encoding=UTF-8
eolMode=CRLF
folds=15,42,48,59,290,1226,1350,1354,1369,1381,1390,1406,1415,1426,1432,1452,1474,1554,1594,1614,2085,2591,2640,2653,2667,2674,2755
[file_004]
path=Loader/Modules/Collision.bas
scroll=33
cursor=0
encoding=UTF-8
eolMode=CRLF
folds=2,11,24,27,30,33,44,63,87,144,161,167,217,399
[file_005]
path=LSModules/LSFunctions.bas
scroll=26
cursor=5310
encoding=UTF-8
eolMode=CRLF
folds=0,13,27,35,60,80,102,145,155,165,230,262,272,283,289,302,307,312,363,376,388,455
[file_006]
path=LSModules/LSViewer.bas
scroll=0
cursor=175
encoding=UTF-8
eolMode=CRLF
folds=14,20,27,51,78,105,118
[file_007]
path=Loader/Modules/ParserFunctions.bas
scroll=11
cursor=0
encoding=UTF-8
eolMode=CRLF
folds=6,35,67,117,140,158,220,248,260,320,326,331,336
[file_008]
path=Loader/ViewModel.bas
scroll=0
cursor=0
encoding=UTF-8
eolMode=CRLF
folds=5,47,105,156,237,286,312,320,366,371,379,419,518,532,662,809,820,831,900,912,990,1015,1071,1154,1184,1232,1258,1299,1313,1516,1652,1667,1672
[browser]
focus=
selected=
[sidebar]
activeTab=subFunction
