@echo off
set F1=%userprofile%\Desktop\LS\Win32\ComboBox.bas
set F2=%userprofile%\Desktop\LS\Win32\LS2LDR.bas
set F3=%userprofile%\Desktop\LS\Win32\Loader\ViewModel.bas
set F4=%userprofile%\Desktop\LS\Win32\Loader\LoadLDR.bas
set F5=%userprofile%\Desktop\LS\Win32\Loader\Modules\Model.bas
set F6=%userprofile%\Desktop\LS\Win32\Loader\ViewModel.bas
set F7=%userprofile%\Desktop\LS\Win32\Loader\PartCheck.bas
set F8=%userprofile%\Desktop\LS\Win32\Loader\Include\Structs.bas

start %F1%
timeout 1
start %F2%
start %F3%
start %F4%
start %F5% 
start %F6%
start %F7%
start %F8%